joint_trajectory_executor:
  ros__parameters:
    joint_names:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    step_names: [home]

    home: [0.0, 0.7770062579651399, 2.1978436317113994, -0.002471903355417154, 1.5707963267948966, -0.008791288084119586]

    duration: 10.0
    epsilon: 0.01
    action_topic: '/arm_controller/follow_joint_trajectory'
    joint_states_topic: '/joint_states'
